# Numpy 배열 연습, python 키워드 인자, \*args, \*\*kwargs 정리

예제) 3x4 배열

In [3]:
import numpy as np
arr_test = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

인덱스 지정

In [6]:
# 모든 행의 첫번째 요소를 가져오기
arr_test[:,1]

array([ 2,  6, 10])

exclusive 지정

In [9]:
# 모든 행의 두번째 까지의 요소를 가져오기 (exclusive)
arr_test[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [10]:
# 모든 행의 첫번째 까지의 요소를 가져오기 (exclusive)
arr_test[:, :1]

array([[1],
       [5],
       [9]])

In [11]:
# 두번째 행까지의 모든 부분 행렬의 모든 요소를 가져오기
arr_test[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

:은 ...으로 바꿔서 쓸수 있다. 둘은 같은 표현이고, 편한것으로 사용한다. 보통은 :를 많이 사용하는 듯 하다.

In [13]:
# 끝에서 첫번째 행의 모든 요소를 ...를 이용해 출력하기
arr_test[-1, ...]

array([ 9, 10, 11, 12])

In [14]:
# 끝에서 첫번째 행의 모든 요소를 :을 이용해 출력하기
arr_test[-1, :]

array([ 9, 10, 11, 12])

In [15]:
# 두번째 행까지 부분배열의 모든 요소들을 출력하기
arr_test[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# 두번째 행에서 세번째행의 부분배열의 모든 요소들을 출력하기
arr_test[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

python의 키워드 인자... 복습  
http://studymake.tistory.com/215

In [25]:
def dict_test():
    return 'name', 'jung'

key, val = dict_test()
print key, val
#print(key, val)

name jung


In [27]:
def test(name, kor=0, math=0, eng=0):
    print name, kor, math, eng
    
test('soon gu', 100, 20, 39)
test('soon young', 20, 20, 20)

soon gu 100 20 39
soon young 20 20 20


python의 \*args, \*\*kwargs
 - **\*args **  
  : 파라미터를 몇개 받을지 모르는 경우 사용한다. args는 튜플 형태로 전달된다.  
 - **\*\*kwargs**  
  **: 파라미터 이름을 지정해서 보낼 수 있다. kwargs는 딕셔너리로 전달된다.**

In [31]:
def print_param(*args):
    print args
    for v in args:
        print v

print print_param('a','b','c','d','e')

('a', 'b', 'c', 'd', 'e')
a
b
c
d
e
None


In [2]:
def print_params2(**kwargs):
    print "**kwargs ..."
    print kwargs
    print ""
    
    print "keys... "
    print kwargs.keys()
    print ""
    
    print "values... "
    print kwargs.values()
    print ""

print({'name':'jung', 'address':'Korea', 'job': 'programmer'})
dict_sample = {'name':'jung', 'address':'Korea', 'job': 'programmer'}

# TypeError: print_params2() takes exactly 0 arguments (1 given)
# print_params2(dict_sample)


print   """
        ===================================
           Printing Keyword Argument
        =================================== 
        """
print_params2(name='jung', job='programmer', address = 'Korea')

{'job': 'programmer', 'name': 'jung', 'address': 'Korea'}

           Printing Keyword Argument
        
**kwargs ...
{'job': 'programmer', 'name': 'jung', 'address': 'Korea'}

keys... 
['job', 'name', 'address']

values... 
['programmer', 'jung', 'Korea']



In [50]:
# 딕셔너리를 선언해서 사용해보기
print   """
        ===============================================
           Printing Keyword Argument using dictionary
        =============================================== 
        """
dict_sample = {'name':'jung', 'address':'Korea', 'job': 'programmer'}
print_params2(**dict_sample)


           Printing Keyword Argument using dictionary
        
**kwargs ...
{'job': 'programmer', 'name': 'jung', 'address': 'Korea'}

keys... 
['job', 'name', 'address']

values... 
['programmer', 'jung', 'Korea']

